### ISSUE TITLE
LOS-Visualizer: Correction of the location coordinates in the wiki

### ISSUE THREAD

**Issue by xa-y-ax** [freifunk-berlin/bbb-configs#696] opened 2024-01-04 11:58 UTC
Please correct the coordinates of the bbb-configs locations in the wiki so that the Line-of-Sight Visualizer can read them correctly.

**Comment by FFHener** [comment] 2024-01-04 12:05
The problem is accuring with the current .kml file. You can see it here:![Bildschirmfoto 2024-01-04 um 11.49.01_20240104130334.png](https://github.com/freifunk-berlin/bbb-configs/assets/93344150/cee60290-2907-4147-a1b0-1c51141e62a2)

Next steps:
- [ ] Does the wiki attributes have the correct xoordinates
- [ ] Does util pull the correct coordinates as seen in the [php-file](https://util.berlin.freifunk.net/line-of-sight.php)

**Comment by FFHener** [comment] 2024-01-09 17:05
I found a way to "solve" the problem. The proplem occured because the locations in the wiki didnt had the `Hat Koordinaten`-Attribute. This behavior happens when we push the coordinates via the API. Apparently it doesnt redo the templates after it. 
What "fixed" it for me was to check out the [Fehlerhafte Annotationen](https://wiki.freifunk.net/Attribut:Hat_Koordinaten), klick edit in the article and directly save it without changing anything or giving a edit message.

This way the "edit" doesnt show up in the version history, but the attribute gets correctly renderd.

Steps to reproduce:

0. Have an article without coordinates
1. Push coordinates via API e.g. use bbb-configs
=> Error, the attribute doesnt exist
2. Press `Quelltext bearbeiten`
3. Press `Änderung speichern`
=> Error fixed

**Comment by FFHener** [comment] 2024-01-09 17:50
Wont fix it any further as there is already a migration path towards having the location pages as a subpage of our website

**Closed by FFHener** 2024-01-09 17:50 UTC
