### ISSUE TITLE
NTP server on the core router for all seconday devices

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/bbb-configs#208] opened 2022-05-11 21:22 UTC
It somehow makes sense to have the core router be the main timekeeper for a location.  If the NTP server is enabled on the core router, then all attached devices can get the time from there.  Also, the generated openwrt based devices could automatically have the ntp server set to the ip addr of the core router.

**Comment by spolack** [comment] 2022-05-17 07:14
Duplicate of #4

**Closed by spolack** 2022-05-17 07:14 UTC
